spring.application.name=ourBankingSystemProject

spring.datasource.url=jdbc:mysql://localhost:3306/banking_db
spring.datasource.username=root
spring.datasource.password=gm18@gaurav

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true